feat: add a secondary `layout` argument in `createStyleSheet`
jpudysz/react-native-unistyles pull request #155
Opened 2024-03-01 17:49 UTC by justblender

## Summary

This PR adds a secondary `layout` argument for the callback function passed into `createStyleSheet`. This is not a breaking change for existing users who only accept one `theme` argument, and will only improve developer experience by providing an easier access to current breakpoint, screen orientation, dimensions, and insets without requiring users to import `UnistylesRuntime` every time.

2024-03-02 14:23 UTC, jpudysz commented
Hey @justblender, thanks for the PR. I think injecting the second argument is a great idea. However, I'm curious, why don't we inject `UnistylesRuntime` itself?

By focusing solely on layout props, we might overlook additional metadata such as `colorScheme`, `hasAdaptiveThemes`, `themeName`, `breakpoints`, and other properties soon to be exposed from the native side. If this approach is intended as a shortcut, it should be equivalent to importing `UnistylesRuntime`.

2024-03-02 14:31 UTC, jpudysz requested changes

2024-03-02 14:31 UTC, jpudysz commented on docs/src/content/docs/reference/create-stylesheet.mdx
> +In addition to the `theme` argument, you can also accept the `layout` argument when passing a function, which can be useful to access screen orientation, dimensions, insets, and more.
accept the `runtime` (...)

2024-03-02 14:31 UTC, jpudysz commented on docs/src/content/docs/reference/create-stylesheet.mdx
> +const stylesheet = createStyleSheet((theme, layout) => ({
`runtime` or `rt`

2024-03-02 14:31 UTC, jpudysz commented on examples/expo/src/examples/RuntimeScreen.tsx
> +const stylesheet = createStyleSheet((theme, layout) => ({
`runtime`/`rt`

2024-03-02 14:31 UTC, jpudysz commented on examples/expo/src/examples/RuntimeWithStyleSheetScreen.tsx
> +const stylesheet = createStyleSheet((theme, layout) => ({
as above

2024-03-02 14:31 UTC, jpudysz commented on src/types/unistyles.ts
> +export type UnistylesLayout = {
we can get rid of this type

2024-03-02 14:31 UTC, jpudysz commented on src/useStyles.ts
> +        ? stylesheet(theme, layout)
`unistyles.runtime`

2024-03-02 14:31 UTC, jpudysz commented on src/types/stylesheet.ts
> +export type StyleSheetWithSuperPowers = ((theme: UnistylesTheme, layout: UnistylesLayout) => StyleSheet) | StyleSheet
`runtime: UnistylesRuntime` imported from `./core`

2024-03-02 14:31 UTC, jpudysz commented on src/types/breakpoints.ts
> +export type ReactNativeStyleSheet<T> = T extends (theme: UnistylesTheme, layout: UnistylesLayout) => infer R
`runtime: UnistylesRuntime` imported from `./core`

2024-03-02 14:31 UTC, jpudysz commented on src/index.ts
> +import type { UnistylesPlugin, UnistylesValues, UnistylesLayout } from './types'
remove

2024-03-02 14:31 UTC, jpudysz commented on src/index.ts
> +    UnistylesLayout
remove

2024-03-02 15:15 UTC, justblender commented
Hey @jpudysz! Yeah, I might've rushed this PR a little bit 😅 Initially I wanted to pass the whole runtime too. I started reconsidering this after noticing that stylesheets are only invalidated when the stylesheet itself, theme or layout changes, so I was concerned that extra runtime properties like `colorScheme` might be out of sync. 

https://github.com/jpudysz/react-native-unistyles/blob/ca4752c8e72e0aa9e5d8fd9b5c98800859f24828/src/useStyles.ts#L28-L30

But after looking again, I might've been mistaken as `colorScheme` change does trigger `onThemeChange` callback, so I guess it would work...

2024-03-02 17:52 UTC, jpudysz reviewed
Also please add yourself to the list of contributors:
https://github.com/jpudysz/react-native-unistyles/blob/bba3e9fc5f894b552a768079d945bda9f101b1d0/docs/src/content/docs/other/sponsors.mdx#L65

2024-03-02 17:52 UTC, jpudysz commented on src/types/breakpoints.ts
> +import type { UnistylesRuntime } from '../core'
use one import

2024-03-03 08:04 UTC, jpudysz approved these changes

2024-03-03 08:07 UTC, merged