chore: better formatting on issue template
jpudysz/react-native-unistyles pull request #33
Opened 2023-10-12 13:47 UTC by efstathiosntonas

## Summary

use `bug-report.yml` instead of `bug-report.md` for better formatting and flow, the .md one was hard to follow when creating a new issue 😄 

[this is how the template will look like from now on](https://github.com/jpudysz/react-native-unistyles/blob/170a6085c5b3b85c1c668224f0732cba36e25c37/.github/ISSUE_TEMPLATE/bug-report.yml)

2023-10-12 18:02 UTC, jpudysz requested changes
Thank you for this improvement, I would remove some fields, as they don't matter with the current implementation

2023-10-12 18:02 UTC, jpudysz commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      label: Snack or a link to a repository
I would add (optional): `Snack or a link to a repository (optional)`

2023-10-12 18:02 UTC, jpudysz commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  - type: dropdown
It can be removed

2023-10-12 18:02 UTC, jpudysz commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  - type: dropdown
This one too, it doesn't matter at this point

2023-10-12 18:02 UTC, jpudysz commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  - type: dropdown
Same here

2023-10-12 18:02 UTC, jpudysz commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  - type: dropdown
Same here, maybe in the future when I add compiler

2023-10-12 18:02 UTC, jpudysz commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  - type: dropdown
same here, works the same everywhere

2023-10-12 18:14 UTC, efstathiosntonas commented
@jpudysz will apply the changes tomorrow!

2023-10-13 09:09 UTC, efstathiosntonas commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        Before you proceed:
@jpudysz which line you mean? L8 or L10?

2023-10-13 09:10 UTC, jpudysz commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        Before you proceed:
entire Line 10

2023-10-13 09:19 UTC, efstathiosntonas commented
@jpudysz I think we're fine now: https://github.com/jpudysz/react-native-unistyles/blob/90868101a9d13f91869d146b049a8c4b65653811/.github/ISSUE_TEMPLATE/bug-report.yml

2023-10-13 12:34 UTC, merged

2023-10-13 12:39 UTC, jpudysz commented
I will update it, no worries. Thanks for spotting it